TARGET = atac_test
SOURCES = atac_test.cc

CORES ?= 5
APP_FLAGS ?= $(CORES) 
ENABLE_SM = true


#CXXFLAGS += -I../../../common/network/
#PP_SPECIFIC_CXX_FLAGS += -I../../../common/network/
include ../../Makefile.tests
